### ISSUE TITLE
Modified date is changed when users add/remove a thread reaction/like

### ISSUE THREAD

**Issue by lily-law** [chingu-voyages/v25-bears-team-05#116]
So we're using the modified date to let the user know this thread was edited n time ago.
Maybe we need to add an extra bit to the mongoose schema to keep a modified time for the thread content.
- Potential solution: for ThreadModel add a timestamp specific to the content portion of the schema so we can use that timeStamp instead.

**Comment by davideastmond** [comment]
PR: https://github.com/chingu-voyages/v25-bears-team-05-repo2/pull/39
