### ISSUE TITLE
SyncedUp App logo should bring user to home page when clicked

### ISSUE THREAD

**Issue by davideastmond** [chingu-voyages/v25-bears-team-05#142]
Issue: Currently when user clicks the logo, nothing happens.
To-do: Implement functionality that takes the user to the SyncedUp homepage when the logo is clicked.

Things to consider: The links will be different depending on whether we are in development or production mode.

**Comment by lily-law** [comment]
So this might be simpler then it seems. In our logo component we just need to wrap in img in a `<Link to="/">`
