### ISSUE TITLE
[BUG] Update mongoose timestamp property on multiple schemas

### ISSUE THREAD

**Issue by davideastmond** [chingu-voyages/v25-bears-team-05#145]
Issue: updatedAt fields on schemas may not be working correct because of syntax like this
`{ timestamps: { }}`
instead of `{ timestamps: true }`

Fix: Update all mongoose schemas to explicitly set the `timestamps` property to true in order to ensure expected timestamp behaviour.

**Comment by lily-law** [comment]
This might be from when we started we pulled in an example like { timestamps: { createdAt: 'created_at' } which does work to set the field under a different name. 

[By default, the names of the fields are createdAt and updatedAt. Customize the field names by setting timestamps.createdAt and timestamps.updatedAt](https://mongoosejs.com/docs/guide.html#timestamps)

Will PR this today
