### ISSUE TITLE
Make route for comments

### ISSUE THREAD

**Issue by lily-law** [chingu-voyages/v25-bears-team-05#146]
We already have a few of the comment methods on the threads route. Though we could do with a get comment by id method, the current get comments method could be updated to get a given array of comment id's. The comment post method makes sense to stay in the thread route. 

So for a discrete comment route (keeping in line with the new page for everything system) we just need to add a get comment by id endpoint, update and move over current get comments method, and move the delete method over from the threads route.

**Comment by davideastmond** [comment]
@lily-law Should we wait until the redux refactor is done for this? I think this will break the front end functionality in the intervening time

**Comment by lily-law** [comment]
Yes, will make sense to do it as a dual frontend+backend PR after the move to redux is merged in. I'll PR 114 now.

**Comment by davideastmond** [comment]
Did you want to take this one? @lily-law
