### ISSUE TITLE
Search UI enhancements

### ISSUE THREAD

**Issue by lily-law** [chingu-voyages/v25-bears-team-05#149]
Add to search page: 
- Back button "Go back to <prev page type: profile|home|network...>"

Add to search component: 
- "X" on right side of input to clear search
- Use new results state in searchSlice (redux) to give some instant local drop down search results. Perform full search on enter
  - Add button to bottom of local drop down search results "Go to search" (equivalent to full search on enter)

This issue is to re-add functionality after changing how search is implemented in PR [114 move to redux](https://github.com/chingu-voyages/v25-bears-team-05/pull/141)

**Comment by davideastmond** [comment]
Also a note to investigate any bugs in relation to search functionality

**Comment by davideastmond** [comment]
How were you thinking the instant local drop down search results should work?

**Comment by lily-law** [comment]
> How were you thinking the instant local drop down search results should work? 
> 
> 

So using the thread/comment/user slice states, we'd filter through them by the query. 
The UI could be styled by having an absolute position wrapper covering 100% width and 100vh - footer and header height. Then the actual drop down can be positioned where needed within with a auto scroll y-overflow...
On enter key or clicking more results button it could redirect to the search page for a full backend search

**Comment by davideastmond** [comment]
Yeah I think this makes sense.
