### ISSUE TITLE
Create a notification component (main menu item)

### ISSUE THREAD

**Issue by davideastmond** [chingu-voyages/v25-bears-team-05#159]
**What:** Create a notification component that is an icon - similar to our current top menu icons.
This icon lights up red to show that a new notification is received. Clicking this icon links to our notification page. 

**How:** Start with Figma design, then create a React component. This may depend on back-end work.

**Why:** Feature enhancement

**Things to consider:**

**Comment by lily-law** [comment]
Should I take this one? or did you want to handle it as part of a front+backend set?

**Comment by davideastmond** [comment]
> Should I take this one? or did you want to handle it as part of a front+backend set?

Hey. I already started a little bit of work on it. It's also a great way for me to learn a bit of redux - so I'll take it 😊

**Comment by lily-law** [comment]
👍
