### ISSUE TITLE
Review and improve user route methods error handling

### ISSUE THREAD

**Issue by lily-law** [chingu-voyages/v25-bears-team-05#75]
Currently we've not implemented checks to confirm the operations are complete, also things like deleting a connection that's not a connection just returns OK 200 as we're only checking if the user exists in the DB not in the users connections...
Most of these things will be masked by the front end UI as normally a user won't be able to perform these actions but we need to consider if on slip through how we want to handle that.

**Comment by davideastmond** [comment]
Is this blocked by refactoring? @lily-law

**Comment by lily-law** [comment]
Nope, it's good to go 👍
